import Transaction from '../models/Transaction.js';
import Category from '../models/Category.js';
import { sendSuccess } from '../utils/apiResponse.js';

const getRangeDates=(range)=>{const now=new Date();const date=new Date(now);if(range==='Week')date.setDate(now.getDate()-7);else if(range==='Month')date.setMonth(now.getMonth()-1);else if(range==='3 Months')date.setMonth(now.getMonth()-3);else date.setFullYear(now.getFullYear()-1);return{start:date,end:now}};

export const getSummaryAnalytics=async(req,res,next)=>{try{const userId=req.user._id;const now=new Date();let periodStart,periodEnd;if(req.query.range){const range=getRangeDates(req.query.range);periodStart=range.start;periodEnd=range.end}else{periodStart=new Date(now.getFullYear(),now.getMonth(),1);periodEnd=new Date(now.getFullYear(),now.getMonth()+1,0,23,59,59,999)}const[allTotals,periodTotals,categorySpend]=await Promise.all([
Transaction.aggregate([{$match:{user:userId}},{$group:{_id:'$type',total:{$sum:'$amount'}}}]),
Transaction.aggregate([{$match:{user:userId,date:{$gte:periodStart,$lte:periodEnd}}},{$group:{_id:'$type',total:{$sum:'$amount'}}}]),
Transaction.aggregate([{$match:{user:userId,type:'Expense',date:{$gte:periodStart,$lte:periodEnd}}},{$group:{_id:'$category',total:{$sum:'$amount'}}},{$sort:{total:-1}},{$limit:1}])
]);const value=(arr,type)=>arr.find(x=>x._id===type)?.total||0;const totalIncome=value(periodTotals,'Income'),totalExpenses=value(periodTotals,'Expense');const allIncome=value(allTotals,'Income'),allExpenses=value(allTotals,'Expense');let highestSpendingCategory='N/A';if(categorySpend[0]){const c=await Category.findOne({_id:categorySpend[0]._id,user:userId}).select('name').lean();if(c)highestSpendingCategory=c.name}const net=totalIncome-totalExpenses;return sendSuccess(res,'Analytics summary fetched',{totalBalance:allIncome-allExpenses,totalIncome,totalExpenses,netSavings:net,savingsRate:totalIncome?(net/totalIncome)*100:0,highestSpendingCategory,currentMonthSpending:totalExpenses,currentMonthIncome:totalIncome})}catch(e){next(e)}};

export const getTrendAnalytics=async(req,res,next)=>{try{const{start,end}=getRangeDates(req.query.range||'Month');const data=await Transaction.aggregate([{$match:{user:req.user._id,date:{$gte:start,$lte:end}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$date'}},income:{$sum:{$cond:[{$eq:['$type','Income']},'$amount',0]}},expenses:{$sum:{$cond:[{$eq:['$type','Expense']},'$amount',0]}}}},{$sort:{_id:1}}]);return sendSuccess(res,'Trend analytics fetched',data)}catch(e){next(e)}};
export const getCategoryAnalytics=async(req,res,next)=>{try{const{start,end}=getRangeDates(req.query.range||'Month');const data=await Transaction.aggregate([{$match:{user:req.user._id,type:'Expense',date:{$gte:start,$lte:end}}},{$group:{_id:'$category',total:{$sum:'$amount'}}},{$sort:{total:-1}},{$limit:10}]);const cats=await Category.find({_id:{$in:data.map(x=>x._id)},user:req.user._id}).select('name').lean();return sendSuccess(res,'Category analytics fetched',data.map(x=>({name:cats.find(c=>String(c._id)===String(x._id))?.name||'Unknown',total:x.total})))}catch(e){next(e)}};
