import { LayoutDashboard, ArrowLeftRight, BarChart3, Wallet, PiggyBank, Goal, Settings, LogOut, Plus } from 'lucide-react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { logoutUser } from '../store/authSlice.js';

const navItems=[
{to:'/dashboard',label:'Dashboard',icon:LayoutDashboard},{to:'/transactions',label:'Transactions',icon:ArrowLeftRight},{to:'/analytics',label:'Analytics',icon:BarChart3},{to:'/accounts',label:'Accounts',icon:Wallet},{to:'/budgets',label:'Budgets',icon:PiggyBank},{to:'/goals',label:'Savings Goals',icon:Goal},{to:'/settings',label:'Settings',icon:Settings},
];
export default function MainLayout(){
  const dispatch=useDispatch();const navigate=useNavigate();const{user}=useSelector(s=>s.auth);
  const logout=async()=>{await dispatch(logoutUser());navigate('/login')};
  return <div className="min-h-screen bg-slate-50 text-slate-900 md:flex">
    <aside className="hidden w-72 flex-col border-r border-slate-200 bg-white p-5 md:flex"><Brand/><nav className="space-y-2">{navItems.map(({to,label,icon:Icon})=><NavLink key={to} to={to} className={({isActive})=>`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium ${isActive?'bg-violet-50 text-violet-700':'text-slate-600 hover:bg-slate-100'}`}><Icon className="h-4 w-4"/>{label}</NavLink>)}</nav><div className="mt-auto rounded-2xl bg-slate-100 p-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-violet-100 font-bold text-violet-700">{user?.name?.charAt(0)?.toUpperCase()||'U'}</div><div className="min-w-0"><p className="truncate text-sm font-semibold">{user?.name||'User'}</p><p className="text-xs text-slate-500">{user?.preferredCurrency||'INR'}</p></div></div><button onClick={logout} className="btn-secondary mt-4 flex w-full items-center justify-center gap-2"><LogOut className="h-4 w-4"/>Logout</button></div></aside>
    <div className="min-w-0 flex-1 pb-20 md:pb-0"><header className="sticky top-0 z-20 border-b border-slate-200 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8"><div className="md:hidden"><Brand compact/></div><div className="hidden md:block"><p className="text-sm text-slate-500">Welcome back</p><h2 className="text-xl font-semibold">{user?.name||'User'}</h2></div><div className="flex items-center gap-2"><button onClick={()=>navigate('/settings')} className="rounded-xl border border-slate-200 p-2.5 text-slate-600 md:hidden" aria-label="Settings"><Settings className="h-4 w-4"/></button><button onClick={()=>navigate('/transactions?add=1')} className="btn-primary flex items-center gap-2"><Plus className="h-4 w-4"/><span className="hidden sm:inline">Add Transaction</span></button><button onClick={logout} className="rounded-xl border border-slate-200 p-2.5 text-slate-600 md:hidden" aria-label="Logout"><LogOut className="h-4 w-4"/></button></div></div></header><main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"><Outlet/></main></div>
    <nav className="fixed inset-x-0 bottom-0 z-30 flex justify-around border-t border-slate-200 bg-white px-1 py-2 md:hidden">{navItems.slice(0,6).map(({to,label,icon:Icon})=><NavLink key={to} to={to} className={({isActive})=>`flex min-w-0 flex-1 flex-col items-center gap-1 rounded-xl px-1 py-2 text-[10px] ${isActive?'text-violet-700':'text-slate-500'}`}><Icon className="h-5 w-5"/><span className="truncate">{label==='Savings Goals'?'Goals':label}</span></NavLink>)}</nav>
  </div>
}
function Brand({compact=false}){return <div className={`flex items-center gap-3 ${compact?'':'mb-8'}`}><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-600 text-lg font-bold text-white">S</div>{!compact&&<div><h1 className="text-xl font-bold">SpendWise</h1><p className="text-xs text-slate-500">Take control of every rupee.</p></div>}</div>}
